name: 'Gatsby CLI wrapper on node12'
description: 'This Action wraps the Gatsby CLI to enable common Gatsby commands. modified fork of jzweifel/gatsby-cli-github-action'
inputs:
  gatsby-arg:
    description: 'Arguments to pass to Gatsby CLI'
    required: true
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gatsby-arg }}
branding:
  icon: 'airplay'  
  color: 'blue'
